import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Brain, ChevronDown, Layers, RefreshCw, Sparkles } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { SiteHeader } from "@/components/lumin/SiteHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useAuth } from "@/hooks/useAuth";
import { supabase } from "@/integrations/supabase/client";
import { createCard, createDeck } from "@/lib/flashcards";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/practice")({
  head: () => ({
    meta: [
      { title: "Adaptive practice — ClearPath by Lumin AI" },
      {
        name: "description",
        content:
          "Optional extra practice questions calibrated to your level, generated by Lumin AI — never your real assignments, just self-testing.",
      },
    ],
  }),
  component: PracticePage,
});

type Difficulty = "beginner" | "intermediate" | "advanced";
type LevelCheckQuestion = { question: string; options: string[]; correctIndex: number };
type PracticeQuestion = { question: string; answer: string; explanation: string };

const DIFFICULTY_LABELS: Record<Difficulty, string> = {
  beginner: "Beginner",
  intermediate: "Intermediate",
  advanced: "Advanced",
};

function PracticePage() {
  const navigate = useNavigate();
  const { user, loading, needsMfa } = useAuth();
  const [subject, setSubject] = useState("");
  const [difficulty, setDifficulty] = useState<Difficulty>("intermediate");

  const [checking, setChecking] = useState(false);
  const [checkQuestions, setCheckQuestions] = useState<LevelCheckQuestion[] | null>(null);
  const [checkAnswers, setCheckAnswers] = useState<number[]>([]);

  const [generating, setGenerating] = useState(false);
  const [questions, setQuestions] = useState<PracticeQuestion[] | null>(null);
  const [revealed, setRevealed] = useState<Set<number>>(new Set());
  const [savingDeck, setSavingDeck] = useState(false);

  useEffect(() => {
    if (loading) return;
    if (!user) {
      void navigate({ to: "/auth" });
      return;
    }
    if (needsMfa) void navigate({ to: "/mfa-challenge" });
  }, [loading, user, needsMfa, navigate]);

  async function authHeader(): Promise<string> {
    const { data } = await supabase.auth.getSession();
    return `Bearer ${data.session?.access_token ?? ""}`;
  }

  async function handleStartLevelCheck() {
    if (!subject.trim()) {
      toast.error("Enter a subject first.");
      return;
    }
    setChecking(true);
    setCheckQuestions(null);
    setQuestions(null);
    try {
      const res = await fetch("/api/adaptive/level-check", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: await authHeader() },
        body: JSON.stringify({ subject: subject.trim() }),
      });
      if (!res.ok) throw new Error("Could not generate a level check right now.");
      const data = (await res.json()) as { questions: LevelCheckQuestion[] };
      setCheckQuestions(data.questions);
      setCheckAnswers(new Array(data.questions.length).fill(-1));
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Could not generate a level check right now.");
    } finally {
      setChecking(false);
    }
  }

  function handleSubmitLevelCheck() {
    if (!checkQuestions) return;
    if (checkAnswers.some((a) => a === -1)) {
      toast.error("Answer every question first.");
      return;
    }
    const correct = checkQuestions.filter((q, i) => q.correctIndex === checkAnswers[i]).length;
    const level: Difficulty = correct >= 4 ? "advanced" : correct >= 2 ? "intermediate" : "beginner";
    setDifficulty(level);
    setCheckQuestions(null);
    toast.success(`You got ${correct}/5 — starting you at ${DIFFICULTY_LABELS[level]}.`);
    void handleGenerate(level);
  }

  async function handleGenerate(useDifficulty?: Difficulty) {
    if (!subject.trim()) {
      toast.error("Enter a subject first.");
      return;
    }
    setGenerating(true);
    setCheckQuestions(null);
    setRevealed(new Set());
    try {
      const res = await fetch("/api/adaptive/practice", {
        method: "POST",
        headers: { "Content-Type": "application/json", Authorization: await authHeader() },
        body: JSON.stringify({ subject: subject.trim(), difficulty: useDifficulty ?? difficulty }),
      });
      if (!res.ok) throw new Error("Could not generate practice questions right now.");
      const data = (await res.json()) as { questions: PracticeQuestion[] };
      setQuestions(data.questions);
    } catch (err) {
      toast.error(
        err instanceof Error ? err.message : "Could not generate practice questions right now.",
      );
    } finally {
      setGenerating(false);
    }
  }

  function toggleReveal(index: number) {
    setRevealed((prev) => {
      const next = new Set(prev);
      if (next.has(index)) next.delete(index);
      else next.add(index);
      return next;
    });
  }

  async function handleSaveFlashcards() {
    if (!user || !questions || questions.length === 0) return;
    setSavingDeck(true);
    try {
      const deck = await createDeck(user.id, {
        title: `${subject} (${DIFFICULTY_LABELS[difficulty]})`,
      });
      for (const q of questions) {
        await createCard(user.id, { deck_id: deck.id, front: q.question, back: q.answer });
      }
      toast.success(`Saved ${questions.length} cards to a new deck.`);
      await navigate({ to: "/flashcards/$deckId", params: { deckId: deck.id } });
    } catch {
      toast.error("Could not save these as flashcards right now.");
    } finally {
      setSavingDeck(false);
    }
  }

  return (
    <div className="min-h-screen bg-deep">
      <SiteHeader />
      <main id="main-content" className="mx-auto max-w-3xl px-6 pb-24">
        <h1 className="text-3xl font-bold">Adaptive practice</h1>
        <p className="mt-2 text-sm text-muted-foreground">
          Optional extra practice questions Lumin invents just for you, calibrated to your level —
          never your real assignments, and full worked answers are fine here since these are
          brand-new practice problems, not your graded work.
        </p>

        <div className="mt-6 grid gap-4 rounded-2xl border border-border/70 bg-card/70 p-6 shadow-panel sm:grid-cols-[1fr_auto]">
          <div>
            <label htmlFor="subject" className="text-xs font-medium text-muted-foreground">
              Subject or topic
            </label>
            <Input
              id="subject"
              value={subject}
              onChange={(e) => setSubject(e.target.value)}
              placeholder="e.g. Quadratic equations, Cell biology, French verb conjugation"
              className="mt-1"
            />
          </div>
          <div>
            <label className="text-xs font-medium text-muted-foreground">Difficulty</label>
            <Select value={difficulty} onValueChange={(v) => setDifficulty(v as Difficulty)}>
              <SelectTrigger className="mt-1 w-40">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {(Object.keys(DIFFICULTY_LABELS) as Difficulty[]).map((d) => (
                  <SelectItem key={d} value={d}>
                    {DIFFICULTY_LABELS[d]}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="flex flex-wrap gap-2 sm:col-span-2">
            <Button
              type="button"
              disabled={generating}
              onClick={() => void handleGenerate()}
              className="gap-1.5 bg-gradient-lumin text-primary-foreground shadow-glow"
            >
              <Sparkles className="h-4 w-4" aria-hidden />
              {generating ? "Generating…" : "Generate practice"}
            </Button>
            <Button
              type="button"
              variant="outline"
              disabled={checking}
              onClick={() => void handleStartLevelCheck()}
              className="gap-1.5 border-border/70 bg-background/40 text-foreground hover:text-foreground"
            >
              <Brain className="h-4 w-4" aria-hidden />
              {checking ? "Preparing…" : "Not sure of your level? Take a 5-question check"}
            </Button>
          </div>
        </div>

        {checkQuestions && (
          <div className="mt-6 space-y-4 rounded-2xl border border-border/70 bg-card/70 p-6 shadow-panel">
            <h2 className="text-lg font-semibold">Quick level check</h2>
            {checkQuestions.map((q, qi) => (
              <div key={qi} className="rounded-xl border border-border/60 bg-background/40 p-4">
                <p className="text-sm font-medium">
                  {qi + 1}. {q.question}
                </p>
                <div className="mt-2 space-y-1.5">
                  {q.options.map((opt, oi) => (
                    <label
                      key={oi}
                      className={cn(
                        "flex cursor-pointer items-center gap-2 rounded-lg border px-3 py-1.5 text-sm transition-colors",
                        checkAnswers[qi] === oi
                          ? "border-accent bg-accent/10"
                          : "border-border/60 hover:border-accent/40",
                      )}
                    >
                      <input
                        type="radio"
                        name={`level-check-${qi}`}
                        className="accent-accent"
                        checked={checkAnswers[qi] === oi}
                        onChange={() =>
                          setCheckAnswers((prev) => prev.map((v, i) => (i === qi ? oi : v)))
                        }
                      />
                      {opt}
                    </label>
                  ))}
                </div>
              </div>
            ))}
            <Button
              type="button"
              onClick={handleSubmitLevelCheck}
              className="bg-gradient-lumin text-primary-foreground shadow-glow"
            >
              Submit and generate practice
            </Button>
          </div>
        )}

        {questions && (
          <div className="mt-6 space-y-3">
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h2 className="text-lg font-semibold">
                {DIFFICULTY_LABELS[difficulty]} practice — {subject}
              </h2>
              <div className="flex gap-1.5">
                <Button
                  type="button"
                  size="sm"
                  variant="outline"
                  disabled={savingDeck}
                  onClick={() => void handleSaveFlashcards()}
                  className="gap-1.5 border-border/70 bg-background/40 text-foreground hover:text-foreground"
                >
                  <Layers className="h-3.5 w-3.5" aria-hidden />
                  {savingDeck ? "Saving…" : "Save as flashcards"}
                </Button>
                <Button
                  type="button"
                  size="sm"
                  variant="ghost"
                  disabled={generating}
                  onClick={() => void handleGenerate()}
                  className="gap-1.5"
                >
                  <RefreshCw className={cn("h-3.5 w-3.5", generating && "animate-spin")} aria-hidden />
                  New set
                </Button>
              </div>
            </div>
            {questions.map((q, i) => (
              <div key={i} className="rounded-xl border border-border/60 bg-card/60 p-4">
                <p className="text-sm font-medium">
                  {i + 1}. {q.question}
                </p>
                <button
                  type="button"
                  onClick={() => toggleReveal(i)}
                  className="mt-2 flex items-center gap-1 text-xs font-medium text-accent"
                  aria-expanded={revealed.has(i)}
                >
                  <ChevronDown
                    className={cn("h-3.5 w-3.5 transition-transform", revealed.has(i) && "rotate-180")}
                    aria-hidden
                  />
                  {revealed.has(i) ? "Hide answer" : "Reveal answer & explanation"}
                </button>
                {revealed.has(i) && (
                  <div className="mt-2 rounded-lg border border-accent/30 bg-accent/5 p-3 text-sm">
                    <p className="font-medium text-accent">{q.answer}</p>
                    <p className="mt-1 text-muted-foreground">{q.explanation}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
