/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSiteChatRouteImport } from './routes/api/site-chat'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api/google-calendar/callback'
import { Route as ApiGoogleCalendarDisconnectRouteImport } from './routes/api/google-calendar/disconnect'
import { Route as ApiGoogleCalendarStartRouteImport } from './routes/api/google-calendar/start'
import { Route as ApiGoogleCalendarSyncRouteImport } from './routes/api/google-calendar/sync'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteChatRoute = ApiSiteChatRouteImport.update({
  id: '/api/site-chat',
  path: '/api/site-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarDisconnectRoute =
  ApiGoogleCalendarDisconnectRouteImport.update({
    id: '/api/google-calendar/disconnect',
    path: '/api/google-calendar/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarStartRoute = ApiGoogleCalendarStartRouteImport.update({
  id: '/api/google-calendar/start',
  path: '/api/google-calendar/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarSyncRoute = ApiGoogleCalendarSyncRouteImport.update({
  id: '/api/google-calendar/sync',
  path: '/api/google-calendar/sync',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/chat/$threadId'
    | '/chat'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSiteChatRoute: typeof ApiSiteChatRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarDisconnectRoute: typeof ApiGoogleCalendarDisconnectRoute
  ApiGoogleCalendarStartRoute: typeof ApiGoogleCalendarStartRoute
  ApiGoogleCalendarSyncRoute: typeof ApiGoogleCalendarSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-chat': {
      id: '/api/site-chat'
      path: '/api/site-chat'
      fullPath: '/api/site-chat'
      preLoaderRoute: typeof ApiSiteChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/disconnect': {
      id: '/api/google-calendar/disconnect'
      path: '/api/google-calendar/disconnect'
      fullPath: '/api/google-calendar/disconnect'
      preLoaderRoute: typeof ApiGoogleCalendarDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/start': {
      id: '/api/google-calendar/start'
      path: '/api/google-calendar/start'
      fullPath: '/api/google-calendar/start'
      preLoaderRoute: typeof ApiGoogleCalendarStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/sync': {
      id: '/api/google-calendar/sync'
      path: '/api/google-calendar/sync'
      fullPath: '/api/google-calendar/sync'
      preLoaderRoute: typeof ApiGoogleCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSiteChatRoute: ApiSiteChatRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarDisconnectRoute: ApiGoogleCalendarDisconnectRoute,
  ApiGoogleCalendarStartRoute: ApiGoogleCalendarStartRoute,
  ApiGoogleCalendarSyncRoute: ApiGoogleCalendarSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
