/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ClassroomRouteImport } from './routes/classroom'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiSiteChatRouteImport } from './routes/api/site-chat'
import { Route as ApiStudyPlanRouteImport } from './routes/api/study-plan'
import { Route as ChatIndexRouteImport } from './routes/chat.index'
import { Route as ChatThreadIdRouteImport } from './routes/chat.$threadId'
import { Route as ApiAdminAdminsRouteImport } from './routes/api/admin/admins'
import { Route as ApiAdminGroupMembersRouteImport } from './routes/api/admin/group-members'
import { Route as ApiAdminGroupsRouteImport } from './routes/api/admin/groups'
import { Route as ApiAdminMeRouteImport } from './routes/api/admin/me'
import { Route as ApiAdminNoticesRouteImport } from './routes/api/admin/notices'
import { Route as ApiAdminSendEmailRouteImport } from './routes/api/admin/send-email'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiGoogleCalendarCallbackRouteImport } from './routes/api/google-calendar/callback'
import { Route as ApiGoogleCalendarDisconnectRouteImport } from './routes/api/google-calendar/disconnect'
import { Route as ApiGoogleCalendarStartRouteImport } from './routes/api/google-calendar/start'
import { Route as ApiGoogleCalendarSyncRouteImport } from './routes/api/google-calendar/sync'
import { Route as ApiGoogleClassroomCallbackRouteImport } from './routes/api/google-classroom/callback'
import { Route as ApiGoogleClassroomDisconnectRouteImport } from './routes/api/google-classroom/disconnect'
import { Route as ApiGoogleClassroomStartRouteImport } from './routes/api/google-classroom/start'
import { Route as ApiGoogleClassroomSyncRouteImport } from './routes/api/google-classroom/sync'
import { Route as ApiMfaBackupCodesClearRouteImport } from './routes/api/mfa-backup-codes/clear'
import { Route as ApiMfaBackupCodesGenerateRouteImport } from './routes/api/mfa-backup-codes/generate'
import { Route as ApiMfaBackupCodesStatusRouteImport } from './routes/api/mfa-backup-codes/status'
import { Route as ApiMfaBackupCodesVerifyRouteImport } from './routes/api/mfa-backup-codes/verify'
import { Route as ApiNotificationsDailyDigestRouteImport } from './routes/api/notifications/daily-digest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassroomRoute = ClassroomRouteImport.update({
  id: '/classroom',
  path: '/classroom',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteChatRoute = ApiSiteChatRouteImport.update({
  id: '/api/site-chat',
  path: '/api/site-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudyPlanRoute = ApiStudyPlanRouteImport.update({
  id: '/api/study-plan',
  path: '/api/study-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatThreadIdRoute = ChatThreadIdRouteImport.update({
  id: '/chat/$threadId',
  path: '/chat/$threadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAdminsRoute = ApiAdminAdminsRouteImport.update({
  id: '/api/admin/admins',
  path: '/api/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGroupMembersRoute = ApiAdminGroupMembersRouteImport.update({
  id: '/api/admin/group-members',
  path: '/api/admin/group-members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGroupsRoute = ApiAdminGroupsRouteImport.update({
  id: '/api/admin/groups',
  path: '/api/admin/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMeRoute = ApiAdminMeRouteImport.update({
  id: '/api/admin/me',
  path: '/api/admin/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNoticesRoute = ApiAdminNoticesRouteImport.update({
  id: '/api/admin/notices',
  path: '/api/admin/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSendEmailRoute = ApiAdminSendEmailRouteImport.update({
  id: '/api/admin/send-email',
  path: '/api/admin/send-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarCallbackRoute =
  ApiGoogleCalendarCallbackRouteImport.update({
    id: '/api/google-calendar/callback',
    path: '/api/google-calendar/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarDisconnectRoute =
  ApiGoogleCalendarDisconnectRouteImport.update({
    id: '/api/google-calendar/disconnect',
    path: '/api/google-calendar/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleCalendarStartRoute = ApiGoogleCalendarStartRouteImport.update({
  id: '/api/google-calendar/start',
  path: '/api/google-calendar/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCalendarSyncRoute = ApiGoogleCalendarSyncRouteImport.update({
  id: '/api/google-calendar/sync',
  path: '/api/google-calendar/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleClassroomCallbackRoute =
  ApiGoogleClassroomCallbackRouteImport.update({
    id: '/api/google-classroom/callback',
    path: '/api/google-classroom/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleClassroomDisconnectRoute =
  ApiGoogleClassroomDisconnectRouteImport.update({
    id: '/api/google-classroom/disconnect',
    path: '/api/google-classroom/disconnect',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGoogleClassroomStartRoute = ApiGoogleClassroomStartRouteImport.update({
  id: '/api/google-classroom/start',
  path: '/api/google-classroom/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleClassroomSyncRoute = ApiGoogleClassroomSyncRouteImport.update({
  id: '/api/google-classroom/sync',
  path: '/api/google-classroom/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMfaBackupCodesClearRoute = ApiMfaBackupCodesClearRouteImport.update({
  id: '/api/mfa-backup-codes/clear',
  path: '/api/mfa-backup-codes/clear',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMfaBackupCodesGenerateRoute =
  ApiMfaBackupCodesGenerateRouteImport.update({
    id: '/api/mfa-backup-codes/generate',
    path: '/api/mfa-backup-codes/generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiMfaBackupCodesStatusRoute = ApiMfaBackupCodesStatusRouteImport.update({
  id: '/api/mfa-backup-codes/status',
  path: '/api/mfa-backup-codes/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMfaBackupCodesVerifyRoute = ApiMfaBackupCodesVerifyRouteImport.update({
  id: '/api/mfa-backup-codes/verify',
  path: '/api/mfa-backup-codes/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsDailyDigestRoute =
  ApiNotificationsDailyDigestRouteImport.update({
    id: '/api/notifications/daily-digest',
    path: '/api/notifications/daily-digest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classroom': typeof ClassroomRoute
  '/grades': typeof GradesRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/api/study-plan': typeof ApiStudyPlanRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/group-members': typeof ApiAdminGroupMembersRoute
  '/api/admin/groups': typeof ApiAdminGroupsRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/notices': typeof ApiAdminNoticesRoute
  '/api/admin/send-email': typeof ApiAdminSendEmailRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
  '/api/google-classroom/callback': typeof ApiGoogleClassroomCallbackRoute
  '/api/google-classroom/disconnect': typeof ApiGoogleClassroomDisconnectRoute
  '/api/google-classroom/start': typeof ApiGoogleClassroomStartRoute
  '/api/google-classroom/sync': typeof ApiGoogleClassroomSyncRoute
  '/api/mfa-backup-codes/clear': typeof ApiMfaBackupCodesClearRoute
  '/api/mfa-backup-codes/generate': typeof ApiMfaBackupCodesGenerateRoute
  '/api/mfa-backup-codes/status': typeof ApiMfaBackupCodesStatusRoute
  '/api/mfa-backup-codes/verify': typeof ApiMfaBackupCodesVerifyRoute
  '/api/notifications/daily-digest': typeof ApiNotificationsDailyDigestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classroom': typeof ClassroomRoute
  '/grades': typeof GradesRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/api/study-plan': typeof ApiStudyPlanRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat': typeof ChatIndexRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/group-members': typeof ApiAdminGroupMembersRoute
  '/api/admin/groups': typeof ApiAdminGroupsRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/notices': typeof ApiAdminNoticesRoute
  '/api/admin/send-email': typeof ApiAdminSendEmailRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
  '/api/google-classroom/callback': typeof ApiGoogleClassroomCallbackRoute
  '/api/google-classroom/disconnect': typeof ApiGoogleClassroomDisconnectRoute
  '/api/google-classroom/start': typeof ApiGoogleClassroomStartRoute
  '/api/google-classroom/sync': typeof ApiGoogleClassroomSyncRoute
  '/api/mfa-backup-codes/clear': typeof ApiMfaBackupCodesClearRoute
  '/api/mfa-backup-codes/generate': typeof ApiMfaBackupCodesGenerateRoute
  '/api/mfa-backup-codes/status': typeof ApiMfaBackupCodesStatusRoute
  '/api/mfa-backup-codes/verify': typeof ApiMfaBackupCodesVerifyRoute
  '/api/notifications/daily-digest': typeof ApiNotificationsDailyDigestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/classroom': typeof ClassroomRoute
  '/grades': typeof GradesRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schedule': typeof ScheduleRoute
  '/tasks': typeof TasksRoute
  '/terms': typeof TermsRoute
  '/api/chat': typeof ApiChatRoute
  '/api/site-chat': typeof ApiSiteChatRoute
  '/api/study-plan': typeof ApiStudyPlanRoute
  '/chat/$threadId': typeof ChatThreadIdRoute
  '/chat/': typeof ChatIndexRoute
  '/api/admin/admins': typeof ApiAdminAdminsRoute
  '/api/admin/group-members': typeof ApiAdminGroupMembersRoute
  '/api/admin/groups': typeof ApiAdminGroupsRoute
  '/api/admin/me': typeof ApiAdminMeRoute
  '/api/admin/notices': typeof ApiAdminNoticesRoute
  '/api/admin/send-email': typeof ApiAdminSendEmailRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/google-calendar/callback': typeof ApiGoogleCalendarCallbackRoute
  '/api/google-calendar/disconnect': typeof ApiGoogleCalendarDisconnectRoute
  '/api/google-calendar/start': typeof ApiGoogleCalendarStartRoute
  '/api/google-calendar/sync': typeof ApiGoogleCalendarSyncRoute
  '/api/google-classroom/callback': typeof ApiGoogleClassroomCallbackRoute
  '/api/google-classroom/disconnect': typeof ApiGoogleClassroomDisconnectRoute
  '/api/google-classroom/start': typeof ApiGoogleClassroomStartRoute
  '/api/google-classroom/sync': typeof ApiGoogleClassroomSyncRoute
  '/api/mfa-backup-codes/clear': typeof ApiMfaBackupCodesClearRoute
  '/api/mfa-backup-codes/generate': typeof ApiMfaBackupCodesGenerateRoute
  '/api/mfa-backup-codes/status': typeof ApiMfaBackupCodesStatusRoute
  '/api/mfa-backup-codes/verify': typeof ApiMfaBackupCodesVerifyRoute
  '/api/notifications/daily-digest': typeof ApiNotificationsDailyDigestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classroom'
    | '/grades'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/api/study-plan'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/admin/admins'
    | '/api/admin/group-members'
    | '/api/admin/groups'
    | '/api/admin/me'
    | '/api/admin/notices'
    | '/api/admin/send-email'
    | '/api/admin/users'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
    | '/api/google-classroom/callback'
    | '/api/google-classroom/disconnect'
    | '/api/google-classroom/start'
    | '/api/google-classroom/sync'
    | '/api/mfa-backup-codes/clear'
    | '/api/mfa-backup-codes/generate'
    | '/api/mfa-backup-codes/status'
    | '/api/mfa-backup-codes/verify'
    | '/api/notifications/daily-digest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classroom'
    | '/grades'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/api/study-plan'
    | '/chat/$threadId'
    | '/chat'
    | '/api/admin/admins'
    | '/api/admin/group-members'
    | '/api/admin/groups'
    | '/api/admin/me'
    | '/api/admin/notices'
    | '/api/admin/send-email'
    | '/api/admin/users'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
    | '/api/google-classroom/callback'
    | '/api/google-classroom/disconnect'
    | '/api/google-classroom/start'
    | '/api/google-classroom/sync'
    | '/api/mfa-backup-codes/clear'
    | '/api/mfa-backup-codes/generate'
    | '/api/mfa-backup-codes/status'
    | '/api/mfa-backup-codes/verify'
    | '/api/notifications/daily-digest'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/classroom'
    | '/grades'
    | '/mfa-challenge'
    | '/privacy'
    | '/reset-password'
    | '/schedule'
    | '/tasks'
    | '/terms'
    | '/api/chat'
    | '/api/site-chat'
    | '/api/study-plan'
    | '/chat/$threadId'
    | '/chat/'
    | '/api/admin/admins'
    | '/api/admin/group-members'
    | '/api/admin/groups'
    | '/api/admin/me'
    | '/api/admin/notices'
    | '/api/admin/send-email'
    | '/api/admin/users'
    | '/api/google-calendar/callback'
    | '/api/google-calendar/disconnect'
    | '/api/google-calendar/start'
    | '/api/google-calendar/sync'
    | '/api/google-classroom/callback'
    | '/api/google-classroom/disconnect'
    | '/api/google-classroom/start'
    | '/api/google-classroom/sync'
    | '/api/mfa-backup-codes/clear'
    | '/api/mfa-backup-codes/generate'
    | '/api/mfa-backup-codes/status'
    | '/api/mfa-backup-codes/verify'
    | '/api/notifications/daily-digest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ClassroomRoute: typeof ClassroomRoute
  GradesRoute: typeof GradesRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScheduleRoute: typeof ScheduleRoute
  TasksRoute: typeof TasksRoute
  TermsRoute: typeof TermsRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSiteChatRoute: typeof ApiSiteChatRoute
  ApiStudyPlanRoute: typeof ApiStudyPlanRoute
  ChatThreadIdRoute: typeof ChatThreadIdRoute
  ChatIndexRoute: typeof ChatIndexRoute
  ApiAdminAdminsRoute: typeof ApiAdminAdminsRoute
  ApiAdminGroupMembersRoute: typeof ApiAdminGroupMembersRoute
  ApiAdminGroupsRoute: typeof ApiAdminGroupsRoute
  ApiAdminMeRoute: typeof ApiAdminMeRoute
  ApiAdminNoticesRoute: typeof ApiAdminNoticesRoute
  ApiAdminSendEmailRoute: typeof ApiAdminSendEmailRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiGoogleCalendarCallbackRoute: typeof ApiGoogleCalendarCallbackRoute
  ApiGoogleCalendarDisconnectRoute: typeof ApiGoogleCalendarDisconnectRoute
  ApiGoogleCalendarStartRoute: typeof ApiGoogleCalendarStartRoute
  ApiGoogleCalendarSyncRoute: typeof ApiGoogleCalendarSyncRoute
  ApiGoogleClassroomCallbackRoute: typeof ApiGoogleClassroomCallbackRoute
  ApiGoogleClassroomDisconnectRoute: typeof ApiGoogleClassroomDisconnectRoute
  ApiGoogleClassroomStartRoute: typeof ApiGoogleClassroomStartRoute
  ApiGoogleClassroomSyncRoute: typeof ApiGoogleClassroomSyncRoute
  ApiMfaBackupCodesClearRoute: typeof ApiMfaBackupCodesClearRoute
  ApiMfaBackupCodesGenerateRoute: typeof ApiMfaBackupCodesGenerateRoute
  ApiMfaBackupCodesStatusRoute: typeof ApiMfaBackupCodesStatusRoute
  ApiMfaBackupCodesVerifyRoute: typeof ApiMfaBackupCodesVerifyRoute
  ApiNotificationsDailyDigestRoute: typeof ApiNotificationsDailyDigestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classroom': {
      id: '/classroom'
      path: '/classroom'
      fullPath: '/classroom'
      preLoaderRoute: typeof ClassroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-chat': {
      id: '/api/site-chat'
      path: '/api/site-chat'
      fullPath: '/api/site-chat'
      preLoaderRoute: typeof ApiSiteChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/study-plan': {
      id: '/api/study-plan'
      path: '/api/study-plan'
      fullPath: '/api/study-plan'
      preLoaderRoute: typeof ApiStudyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$threadId': {
      id: '/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof ChatThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/admins': {
      id: '/api/admin/admins'
      path: '/api/admin/admins'
      fullPath: '/api/admin/admins'
      preLoaderRoute: typeof ApiAdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/group-members': {
      id: '/api/admin/group-members'
      path: '/api/admin/group-members'
      fullPath: '/api/admin/group-members'
      preLoaderRoute: typeof ApiAdminGroupMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/groups': {
      id: '/api/admin/groups'
      path: '/api/admin/groups'
      fullPath: '/api/admin/groups'
      preLoaderRoute: typeof ApiAdminGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/me': {
      id: '/api/admin/me'
      path: '/api/admin/me'
      fullPath: '/api/admin/me'
      preLoaderRoute: typeof ApiAdminMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notices': {
      id: '/api/admin/notices'
      path: '/api/admin/notices'
      fullPath: '/api/admin/notices'
      preLoaderRoute: typeof ApiAdminNoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/send-email': {
      id: '/api/admin/send-email'
      path: '/api/admin/send-email'
      fullPath: '/api/admin/send-email'
      preLoaderRoute: typeof ApiAdminSendEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/callback': {
      id: '/api/google-calendar/callback'
      path: '/api/google-calendar/callback'
      fullPath: '/api/google-calendar/callback'
      preLoaderRoute: typeof ApiGoogleCalendarCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/disconnect': {
      id: '/api/google-calendar/disconnect'
      path: '/api/google-calendar/disconnect'
      fullPath: '/api/google-calendar/disconnect'
      preLoaderRoute: typeof ApiGoogleCalendarDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/start': {
      id: '/api/google-calendar/start'
      path: '/api/google-calendar/start'
      fullPath: '/api/google-calendar/start'
      preLoaderRoute: typeof ApiGoogleCalendarStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-calendar/sync': {
      id: '/api/google-calendar/sync'
      path: '/api/google-calendar/sync'
      fullPath: '/api/google-calendar/sync'
      preLoaderRoute: typeof ApiGoogleCalendarSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-classroom/callback': {
      id: '/api/google-classroom/callback'
      path: '/api/google-classroom/callback'
      fullPath: '/api/google-classroom/callback'
      preLoaderRoute: typeof ApiGoogleClassroomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-classroom/disconnect': {
      id: '/api/google-classroom/disconnect'
      path: '/api/google-classroom/disconnect'
      fullPath: '/api/google-classroom/disconnect'
      preLoaderRoute: typeof ApiGoogleClassroomDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-classroom/start': {
      id: '/api/google-classroom/start'
      path: '/api/google-classroom/start'
      fullPath: '/api/google-classroom/start'
      preLoaderRoute: typeof ApiGoogleClassroomStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-classroom/sync': {
      id: '/api/google-classroom/sync'
      path: '/api/google-classroom/sync'
      fullPath: '/api/google-classroom/sync'
      preLoaderRoute: typeof ApiGoogleClassroomSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mfa-backup-codes/clear': {
      id: '/api/mfa-backup-codes/clear'
      path: '/api/mfa-backup-codes/clear'
      fullPath: '/api/mfa-backup-codes/clear'
      preLoaderRoute: typeof ApiMfaBackupCodesClearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mfa-backup-codes/generate': {
      id: '/api/mfa-backup-codes/generate'
      path: '/api/mfa-backup-codes/generate'
      fullPath: '/api/mfa-backup-codes/generate'
      preLoaderRoute: typeof ApiMfaBackupCodesGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mfa-backup-codes/status': {
      id: '/api/mfa-backup-codes/status'
      path: '/api/mfa-backup-codes/status'
      fullPath: '/api/mfa-backup-codes/status'
      preLoaderRoute: typeof ApiMfaBackupCodesStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mfa-backup-codes/verify': {
      id: '/api/mfa-backup-codes/verify'
      path: '/api/mfa-backup-codes/verify'
      fullPath: '/api/mfa-backup-codes/verify'
      preLoaderRoute: typeof ApiMfaBackupCodesVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/daily-digest': {
      id: '/api/notifications/daily-digest'
      path: '/api/notifications/daily-digest'
      fullPath: '/api/notifications/daily-digest'
      preLoaderRoute: typeof ApiNotificationsDailyDigestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ClassroomRoute: ClassroomRoute,
  GradesRoute: GradesRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScheduleRoute: ScheduleRoute,
  TasksRoute: TasksRoute,
  TermsRoute: TermsRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSiteChatRoute: ApiSiteChatRoute,
  ApiStudyPlanRoute: ApiStudyPlanRoute,
  ChatThreadIdRoute: ChatThreadIdRoute,
  ChatIndexRoute: ChatIndexRoute,
  ApiAdminAdminsRoute: ApiAdminAdminsRoute,
  ApiAdminGroupMembersRoute: ApiAdminGroupMembersRoute,
  ApiAdminGroupsRoute: ApiAdminGroupsRoute,
  ApiAdminMeRoute: ApiAdminMeRoute,
  ApiAdminNoticesRoute: ApiAdminNoticesRoute,
  ApiAdminSendEmailRoute: ApiAdminSendEmailRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiGoogleCalendarCallbackRoute: ApiGoogleCalendarCallbackRoute,
  ApiGoogleCalendarDisconnectRoute: ApiGoogleCalendarDisconnectRoute,
  ApiGoogleCalendarStartRoute: ApiGoogleCalendarStartRoute,
  ApiGoogleCalendarSyncRoute: ApiGoogleCalendarSyncRoute,
  ApiGoogleClassroomCallbackRoute: ApiGoogleClassroomCallbackRoute,
  ApiGoogleClassroomDisconnectRoute: ApiGoogleClassroomDisconnectRoute,
  ApiGoogleClassroomStartRoute: ApiGoogleClassroomStartRoute,
  ApiGoogleClassroomSyncRoute: ApiGoogleClassroomSyncRoute,
  ApiMfaBackupCodesClearRoute: ApiMfaBackupCodesClearRoute,
  ApiMfaBackupCodesGenerateRoute: ApiMfaBackupCodesGenerateRoute,
  ApiMfaBackupCodesStatusRoute: ApiMfaBackupCodesStatusRoute,
  ApiMfaBackupCodesVerifyRoute: ApiMfaBackupCodesVerifyRoute,
  ApiNotificationsDailyDigestRoute: ApiNotificationsDailyDigestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
